spring:
  application:
    name: policy-service
  r2dbc:
    url: r2dbc:h2:mem:///policydb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    sql:
      init:
        mode: always

server:
  port: 8080

payment:
  base-url: http://localhost:8081
  timeout-ms: 2000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics